language: python

sudo: false

python:
- '2.7'
- '3.5'
- '3.6'
before_install:
  - export DJANGO_SETTINGS_MODULE=bucketlists.settings
install:
- pip install -r requirements.txt
- pip install coveralls

script:
- nosetests --with-coverage --cover-package api_v1
after_success: coveralls
cache: pip
