language: python

sudo: false

python:
- '2.7'
- '3.5'
- '3.6'
before_install:
  - export DJANGO_SETTINGS_MODULE=bucketlists.settings.settings
install:
- pip install -r requirements.txt
- pip install coveralls
addons:
  postgresql: '9.4'
before_script:
- psql -c 'CREATE DATABASE buckos;' -U postgres

script:
- python manage.py makemigrations
- python manage.py migrate
- nosetests --with-coverage --cover-package api_v1
after_success: coveralls
cache: pip
