language: python

sudo: false

python:
- '2.7'
- '3.5'
- '3.6'
install:
- pip install -r requirements.txt
- pip install coveralls
script:
- nosetests --with-coverage --cover-package api_v1
after_success: coveralls
cache: pip